### ISSUE TITLE
Golden校准程序图像有条纹

### ISSUE THREAD

**Issue by deism** [Eastzonetech/GOLDEN-DF-VRN#3]
采用Vairian校准程序图像正常。打开图像时候头信息的尺寸是否准确

**Comment by teamsoftware123** [comment]
据我所知，并非如此，使用我们的软件做校准图像也是正常的，动态采集时候图像是正常的，只是积分后图像后条纹，原因我还在找，应该马上能够解决。

**Comment by teamsoftware123** [comment]
该问题已经解决，是因为积分时会停止采集，然后再重新开始采集从而导致这个问题，目前解决方案是不停止采集，在实时采集过程中抽取帧数进行积分，从而以消除背景条纹。
